[package]
name = "advent2021"
version = "0.1.0"
authors = ["Haochuan Liu <haochuan.liu@gmail.com>"]
edition = "2018"


[dependencies]
structopt = { version = "0.3", default-features = false }
itertools = "0.9.0"
